---
title: "Ecoli Genome Analysis"
author: "Trevor Schaff"
date: "October 12, 2015"
output: html_document
---
Here I'm working with the data carpentry ecoli genomes data set. I found it at this website: http://tracykteal.github.io/R-genomics/02-starting-with-data.html

```{r set seed, echo=TRUE, eval=TRUE}
set.seed(65870179)
```

Below I am importing the **ecoli** data from our data folder.

```{r Import Data, echo = TRUE, eval = TRUE}
metadata <- read.csv('data/Ecoli_metadata.csv') #Reading in my data file into an object named metadata
#View(metadata) #looking at the table within R
#str()
#?str #get help on str
#??str #all help pages with str in it
str(metadata) # looking at structure of data frame
mean(metadata$genome_size) # calculating the mean

```

```{r load packages, eval=TRUE}
#install.packages("ggplot2")
library(ggplot2)
```

```{r data exploration, echo = TRUE, eval = TRUE, fig.center = TRUE}
ggplot(metadata, aes(x = genome_size)) + geom_bar(stat = "bin", binwidth=0.01) #creates bar graph

```

Always include session info for reproducible documents!
```{r session info}
#install.packages("devtools")
#library(devtools)
devtools::session_info()

```